# Project Information
pluginGroup=com.eliteessentials
pluginVersion=2.0.8
pluginDescription=Essential commands for Hytale servers - homes, teleports, and more
serverVersion=0.5.1

# Java settings
java_version=25

# Gradle Configuration
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
